Add logout data into the authservice chain
defenseunicorns/pepr-keycloak-authsvc pull request #59
Opened 2023-06-26 20:14 UTC by kirankt

This PR adds the logout fields in the authservice chain to enable an app (keycloak client) to hit the /logout resource to logout of keycloak.

The logout URI uses the format listed in keycloak docs:
https://www.keycloak.org/docs/latest/securing_apps/index.html#logout

Closes #53

2023-06-26 20:50 UTC, bburky requested changes

2023-06-26 20:50 UTC, bburky commented on capabilities/lib/authservice/secretBuilder.ts
> +        logout_redirect_uri: `https://keycloak.${domain}/auth/realms/${realm}/protocol/openid-connect/logout`,
You want to also include the client id in the logout URI:
```suggestion
        logout_redirect_uri: `https://keycloak.${domain}/auth/realms/${realm}/protocol/openid-connect/logout/?client_id=${id}`,
```

If you view your user's sessions on keycloak in the browser, you should see the name of this client go away if the logout was successful

2023-06-28 18:22 UTC, bburky approved these changes
I think this looks good, the logout url is correct I think. I haven't tested this, but I think this structure makes sense.

2023-06-28 18:52 UTC, bdw617 requested changes
hold off for now, we'll get to this later if needed. @brianrexrode didn't think we needed this yet.

2023-06-29 15:48 UTC, bdw617 commented
I'm going to close this for now, we can revisit it if needed :)

2023-06-29 15:48 UTC, closed without merging